env:
  # Telegram
  TG_CHAT: "@hopireika_dump"
  TG_TOKEN: "ENCRYPTED[95fdfa1f0da96e7f87ebd98cd586541dcc48af664a501fbedac07efd4b11bdc4c502b2a070d0c1de5cbd544b57b77cfe]"

  # Github
  GITHUB_ORG: PineapleDUMP
  GITHUB_TOKEN: "ENCRYPTED[9819487f0fb57027a6244b42ff23d93202ced795c6e7b796f15cfd2c39e1943baea89f837d31b676bc16e27ea13e5c7c]"

task:
  name: "Firmware Dumper"
  timeout_in: 120m
  container:
      image: kizziama/ubuntu:latest
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/Kizziama/DumprX.git ~/DumprX

  Setup_script:
      - git config --global user.name "Kizziama"
      - git config --global user.email "kizziama@proton.me"
      - git config --global color.ui auto
      - cd ~/DumprX
      - echo "${GITHUB_TOKEN}" > .github_token
      - echo "${GITHUB_ORG}" > .github_orgname
      - echo "${TG_CHAT}" > .tg_chat
      - echo "${TG_TOKEN}" > .tg_token
      - bash setup.sh

  DumprX_script:
      - cd ~/DumprX
      - ./dumper.sh $(cat ${CIRRUS_WORKING_DIR}/URL.txt)
